### ISSUE TITLE
File events status

### ISSUE THREAD

**Issue by t45l0** [rabbitstack/fibratus#106]
Hi @rabbitstack,
I am trying to analyze all the file operations related to a specific process and I'd like to use also the "not found" events. For example, MS Procmon provides all the *CreateFile* events, also in the case of a name/path not found.

In particular, wrt *registry* events, the *status* flag is not available for *file* events. 

Is it possible to solve such a problem using a specific configuration?

**Comment by rabbitstack** [comment]
Hey @t45l0 

This would require a small change to format the NT status code which is present in event parameters.

Let me know if you are up for putting together a PR and I could provide further guidelines with implementation details.

**Comment by t45l0** [comment]
Thanks a lot!
I'm quite new in programming with Go, but I'll try to do that certainly.
I look forward to receiving your guidelines.

**Comment by rabbitstack** [comment]
Hi @t45l0 

It is a low-hanging fruit, so I think it should be quite straightforward to implement even if you're new with Go.

I'll try to summarize the steps needed:

1. The `FileOpEnd` event contains the NT status code of the file operation. You can consult the raw status parameter and convert it to human-readable message. Then you simply append the parameter like [this](https://github.com/rabbitstack/fibratus/blob/a5c0c29f38bbf20bae74d7901471cecd44dbb80c/pkg/kstream/interceptors/fs_windows.go#L247).

```go
status, err := kevt.Kparams.GetUint32(kparams.NTStatus)
if err == nil {
	_ = kevt.Kparams.Set(kparams.NTStatus, formatStatus(status), kparams.UnicodeString)
}
```

The [`formatStatus`](https://github.com/rabbitstack/fibratus/blob/a5c0c29f38bbf20bae74d7901471cecd44dbb80c/pkg/kstream/interceptors/registry_windows.go#L226) function has an unfortunate fast lookup path with a hardcoded registry `key not found` status message. In order to preserve the backward compatibility, but still, be able to have a different error message for the `file not found` status code, I suggest modifying the function:
 - move the function to let's say `pkg/kstream/interceptors/util.go` source file
 - adjust the function to accept the `kevt` reference, so we can accordingly distinguish between file, registry or other not found error messages

```
func formatStatus(status uint32, kevt *kevent.Kevent) string {
	if status == 0 {
		return "success"
	}
	// this status code is return quite often so we can offload the FormatMessage call
	if status == notFoundNTStatus {
                 switch kevt.Category {
                 case ktypes.Registry:
                     return "key not found"
                 case ktypes.File:
                     return "file not found"
                 }
	}
	// pick resolved status
	if s, ok := resolvedStatuses[status]; ok {
		return s
	}
	var flags uint32 = syscall.FORMAT_MESSAGE_FROM_SYSTEM
	b := make([]uint16, 300)
	n, err := windows.FormatMessage(flags, 0, sys.CodeFromNtStatus(status), 0, b, nil)
	if err != nil {
		return "unknown"
	}
	// trim terminating \r and \n
	for ; n > 0 && (b[n-1] == '\n' || b[n-1] == '\r'); n-- {
	}

	s := strings.ToLower(string(utf16.Decode(b[:n])))
	resolvedStatuses[status] = s

	return s
}
```

2. Add a new `file.status` filter field [here](https://github.com/rabbitstack/fibratus/blob/a5c0c29f38bbf20bae74d7901471cecd44dbb80c/pkg/filter/fields/fields_windows.go#L384) and augment the [file](https://github.com/rabbitstack/fibratus/blob/a5c0c29f38bbf20bae74d7901471cecd44dbb80c/pkg/filter/accessor_windows.go#L471) accessor to obtain the status message. This would allow building filter expressions like `file.status contains 'not found'`.

Let me know if you have any questions.
