### ISSUE TITLE
Strange Characters In Replay Stream

### ISSUE THREAD

**Issue by repmop** [rabbitstack/fibratus#117]
I ran:
```
fibratus capture -o log.kcap ps.name in ('myprog.exe')
fibratus replay -k log.kcap
```

And I'm seeing lots of events that seem correct, but scattered throughout I'm seeing characters that are not recognized by powershell (see attached png)
I tried different text renderers, but I'm not sure what these characters are meant to be. Any thoughts?
![fibratus](https://user-images.githubusercontent.com/25692161/171521593-09295f5c-24a0-46b5-aaec-bffc5e000ffd.png)

**Comment by rabbitstack** [comment]
Hi @repmop 

This is probably caused by the terminal Unicode rendering issue. If you switch to Windows Terminal or Cmder this shouldn't appear to be a problem. Nevertheless, you can completely change the parameter separator by editing the fibratus config file. See this [link](https://www.fibratus.io/#/outputs/console?id=kv-delimiter)

**Comment by repmop** [comment]
Thanks! Odd that the default character wasn't preserved after redirect (or maybe the renderers I tried are just no good).
