### ISSUE TITLE
skips images in fibratus.yml do not work

### ISSUE THREAD

**Issue by jialongzhang** [rabbitstack/fibratus#18]
I put explorer.exe under skips images in fibratus.yml. When I start fibratus, I can see the output like "Fibratus: Adding skips for images ['explorer.exe',...]". However, from the traces, there are still lots of events generated by explorer.exe.

**Comment by rabbitstack** [comment]
Does it happen with all kind of events?

**Comment by jialongzhang** [comment]
I am not exactly sure. However, I see lots of my filtered images are still there.

**Comment by jialongzhang** [comment]
![fibratus](https://cloud.githubusercontent.com/assets/21164042/24916876/71f2ac84-1ea9-11e7-8674-c20cc686ff3b.jpg)

Also I see some garbled image names. In this case, it should be notepad.exe

**Comment by rabbitstack** [comment]
@jialongzhang I'll try to reproduce it and should eventually be fixed in the next release. Regarding garbled image names, might be due to some incosistency while invoking `QueryFullProcesImageName` or `ZwQueryFileInformation` functions when thread registry lookup fails. Could you please create another issue so I can track and fix it soon?
