### ISSUE TITLE
Run fibratus without any alert sender running

### ISSUE THREAD

**Issue by Muskra** [rabbitstack/fibratus#373]
**Motivation**

I'm a security researcher that pass a lot of time analysing executables for assessments. I'm sick of non scalable tools like procmon and other proprietary tools that are really old and clunky. You tool feel's like it can cut the bread for my use cases.

**Feature**

Add the possibility to run fibratus local only and provides logging directly in files, without any network requirements or external tools/services. I need the logs on the computer directly, not on a server. It's better that way, especially when you can't afford an internet connection on the machine (like in hardly isolated environments).

**Alternatives**

More complex way of doing the thing locally is by exporting the whole logs into pcap files. I know that android's ADB logging tools can do those kind of output which is really handy and nice to have to filter afterward in an assessment.

**Additional context**

This tool could be a really nice EDR solution, but there is actually no EDR capable of being used as a usable tool rather than a reporting tool. And i think it's not just a niche topic, it could be really really good in addition with with all of the proprietary tools that Microsoft is providing.

**Maybe i'm wrong and the feature already exist ?**

Anyway, thanks for this great piece of software :)

**Comment by rabbitstack** [comment]
Hey @Muskra ,

Thanks for the encouraging words and for submitting your feature request :). The only alertsender that gets enabled by default is systray alertsender. You can disable it by setting the [enabled ](https://github.com/rabbitstack/fibratus/blob/bd07273f0b16ad7ed28e82f61fecb0cd526aa44a/configs/fibratus.yml#L22)attribute in the config file to `false`. Still, you'll have the full alert context in the Fibratus logs. Just grep for `sending alert` substring. This is when it comes to alerts generated by the behavior detection engine or the memory scanner. 

If you run Fibratus in [event-forwarding](https://www.fibratus.io/#/setup/quick-start?id=event-forwarding) mode, by default, it will dump all captured events to the console. Alternatively, you can write all events into the `kcap` file, which is semantically similar to `pcap` files, but instead of packets, it stores system events with the full process state.

For example. You can capture all network, process, and memory events.

```
fibratus capture "kevt.category in ('net', 'process', 'mem')" -o events.kcap
```

With the kcap generated, you can use it to reconstruct the event flow, possibly providing filter expressions:

```
fibratus replay "ps.name = 'svchost.exe'" -k events.kcap
```

More info on captures: https://www.fibratus.io/#/captures/capturing

I hope this fulfills your needs. If this is not the case, we can work together to provide a better solution.

Thanks,

**Comment by rabbitstack** [comment]
If I'm parsing the error message correctly, you may be using the latest Fibratus version (2.2.1), whereas the config file is taken from the master branch? Or perhaps you built Fibratus from the source?

I'm assuming this because the `eventlog` sender is not part of any release. This is the functionality that is still in development phase and will be shipped  in the next release.

And sure, you can disable all alertsenders. In fact, all alertsenders but systray are disabled by default.

**Comment by Muskra** [comment]
I'll look at the version i got because i can't remember. But think i'm using the last release one from the git as binary. I'm never compiling a security tool from the main because of reliability requirements tho, only from releases if required. The error i got was with all alertsenders deactivated so you may be right on the version thing. I'll reach you out tomorrow if i found the time to :)

**Comment by rabbitstack** [comment]
If you get rid of the `alertsenders.eventlog` line, the error message should vanish. It is basically being confused because the validation against the JSON schema is failing. Expected, since eventlog alertsender is not a thing in version 2.2.1

**Comment by Muskra** [comment]
Hi, you last comment debugged me. The problem was me trying to use the latest config from the main repo (took it on my main computer then uploaded on the vm to test it out). Simple stupid error, i should have downloaded the config file from the release i'm using, notes taken on that one. Thanks for the help !

**Comment by rabbitstack** [comment]
Nice! Don't hesitate to reach out if you need help with anything else.

Regards
