### ISSUE TITLE
How I know which process execute the file operation?

### ISSUE THREAD

**Issue by HaiLanLin** [rabbitstack/fibratus#96]
I'm  new about fibratus. And I can get events data when using cmd to excute "fibratus run > C:/1.txt" command. But the file events  is such as "303340 2021-09-28 17:18:20.9101198 +0800 CST - 0 . (4294967295) - ReadFile (file_name➜ C:\pagefile.sys, file_object➜ fffffa80028cb4a0, io_size➜ 16384, irp➜ fffffa80034b7a80, offset➜ 442601472, type➜ file)". I can not get relations about this file event with the original process. So what should i do?

**Comment by rabbitstack** [comment]
Does this happen for each event or you're seeing this occasionally? Which Windows version is this?

btw. If you want to capture events and reply afterward, you can use [kcaps](https://www.fibratus.io/#/captures/capturing).

**Comment by rabbitstack** [comment]
I think this might be the case in Windows 7 where the ETW provider emits the file-related events with invalid pid, but fibratus does the best effort to deduce the pid from the thread identifier. Of course, this can fail if the handle to the thread identifier can't be obtained, because the thread is running in a system process.

So, all events have invalid pid? Or just file events?

kcaps are replied with the `reply` command. See the [docs](https://www.fibratus.io/#/captures/replaying). So, if you want to reply only file events where the file name ends with `.sys`, you could use the following command:

```
fibratus replay kevt.category = 'file' and file.extension = '.sys'
```

Learn more about filters [here](https://www.fibratus.io/#/filters/introduction).

**Comment by HaiLanLin** [comment]
Thanks lot, It is indeed a problem with windows7. When I run fibratus on windows10, the data obtained is normal. I can use these data for further analysis. In short, thank you very much!

**Comment by rabbitstack** [comment]
Glad you were able to solve the issue!
